const express = require('express');
const router = express.Router();
//Libraraies -------------------
const Joi = require("Joi");
const uniqid = require("uniqid");
//Import RestaurantsData
let HotelsData = require('./HotelsData.json');

// ---------------------------------- MIDDLEWARES -----------------------------------------

//>------- VALIDATE HOTEL'S DATA ----------->
function validateHotel(req,res,next){
    
    const hotel = req.body;
    //CHECKING EVERY VALUE TO SEE IF THEIR FORMAT IS CORRECT :
    //Creating the scheme validation :
    const schema = Joi.object({

        // id : Joi.number().integer().min(3).strict().required(),
        name : Joi.string().min(1).max(30).required(),
        address : Joi.string().min(5).max(90).required(),
        city : Joi.string().min(1).max(30).required(),
        country : Joi.string().min(1).max(30).required(),
        stars :  Joi.number().integer().min(1).max(5).strict().required(),
        hasSpa : Joi.boolean().strict().required(),
        hasPool : Joi.boolean().strict().required(),
        priceCategory :  Joi.number().integer().min(1).max(3).strict().required(),
    })

    const validateHotelInfos = schema.validate(hotel);
    //Guard : 
    if (validateHotelInfos.error) {
        return res.status(400).json({
            message : validateHotelInfos.error.details[0].message,
        })
    }

    next();
}

//>------- CHECK IF HOTEL NAME ALREADY EXISTS ----------->
function checkIfHotelNameAlreadyExists(req,res,next) {

    if (req.params.name) {
        
        //If the param name is found in the hotel database, then an error message is displayed : 
        if (HotelsData.filter(hotel => hotel.name.toLowerCase().replace(' ', '-') === req.params.name.toLowerCase().replace(' ', '-')).length <= 0) {
            req.paramsNameExists = false;
            return res.status(404).json({message : "This hotel doesn't exist in our database. "})
            
        } else {
            req.paramsNameExists = true;
        }   console.log("true : ",req.paramsNameExists);
    }

    if (req.body.name) {
        
        if (HotelsData.filter(hotel => hotel.name.toLowerCase().replace(' ', '-') === req.body.name.toLowerCase().replace(' ', '-')).length <= 0) {
            req.bodyNameExists = false;
            //If the body name is found in the hotel database, then an error message is displayed : 
        } else {
            req.bodyNameExists = true;
            return res.status(404).json({message : "This hotel already exists. Please choose another name."})
        }
    }

    next();
}

// >-------FIND HOTEL BY ID ----------->
function findHotelByID(req,res,next) {

    const id = req.params.id;
    
    const hotel = HotelsData.find(hotel => {
        return hotel.id.toString() === id;
    })

    if (hotel === undefined) {
        return res.status(404).json({message : "This hotel doesn't exist. "})
    }

    req.hotel = hotel;

    next();
}

// >------- ADD RANDOM ID ----------->
function addRandomID(req,res,next) {
    req.randomID = uniqid();
    req.body.id = req.randomID;
    next();
   };

// ----------------------------------------- ROUTES -----------------------------------------
//------------------------------ WE ARE IN : localhost:8000/hotels/ -------------------------

//GET THE LIST OF ALL HOTELS  : 
router.get('/', (req,res) => {
    res.status(201).json(HotelsData);
})

//GET A HOTEL BY ITS ID: 
router.get('/:id', findHotelByID, (req,res) => {

    let id = req.params.id;
    const hotel = HotelsData.find(hotel => {
        return hotel.id.toString() === id;  
    })
    
    return res.status(201).json(hotel);
})

//ADD A NEW HOTEL : 
router.post('/',checkIfHotelNameAlreadyExists, validateHotel,addRandomID, (req,res)=> {
    const hotel = req.body;
    HotelsData.push(hotel);
    res.status(201).json({message : "Hotel added !", hotels : HotelsData});

})

//UPDATE A HOTEL'S NAME : 
router.patch('/:name', checkIfHotelNameAlreadyExists, (req,res) => {
    const currentName = req.params.name;
    const newName = req.body.name;
    const hotelExists = req.paramsNameExists ;
    const nameAlreadyExists = req.bodyNameExists ;
   
    //Find hotel : 
    let hotel = HotelsData.find(hotel => {
        return hotel.name.toLowerCase().replace(' ', '-') === currentName.toLowerCase().replace(' ', '-');  
    })

    //Checking if the name is a string :
    const scheme = Joi.object({
        name : Joi.string().min(1).max(30).required(),
    })

    const validateName = scheme.validate(req.body);

    //Guard : 
    if (validateName.error) {
        return res.status(400).json({
            message : validateName.error.details[0].message,
        })
    }

    //Updating the hotel's name in the database:
    hotel.name = newName;
    return res.status(201).json({message : "Hotel's name updated !", hotel}); 
})

router.delete('/:id', findHotelByID, (req,res) => {
    //Getting the hotel from the req params, generated by the findHotelByID middleware :
    const deletedHotel = req.hotel;

    //Delete function :
    HotelsData = HotelsData.filter(hotel => {
        return hotel !== deletedHotel;
    })

    return res.status(201).json({message : ` ${deletedHotel.name} Hotel successfully deleted !`, hotels : HotelsData});
})


// Exporting the router
module.exports = router;